# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='char',
            old_name='attack',
            new_name='attack_max',
        ),
        migrations.RenameField(
            model_name='char',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mon',
            old_name='attack',
            new_name='attack_max',
        ),
        migrations.RemoveField(
            model_name='char',
            name='last_name',
        ),
        migrations.AddField(
            model_name='char',
            name='attack_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='char',
            name='exp_to_level',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='char',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mon',
            name='attack_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
