# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0002_auto_20180416_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monsters_killed',
            field=models.ManyToManyField(related_name='slayers', to='dungeon_app.Mon'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_dmg_dealt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_dmg_taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
