# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0003_auto_20180416_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon',
            name='defense',
        ),
    ]
