# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0006_auto_20180416_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon',
            name='job',
        ),
        migrations.RemoveField(
            model_name='mon',
            name='level',
        ),
    ]
