# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0007_auto_20180416_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='armor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armor_wearers', to='dungeon_app.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='char',
            name='weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_wielders', to='dungeon_app.Item'),
            preserve_default=False,
        ),
    ]
