# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0009_auto_20180416_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='armor',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='potion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weapon',
        ),
    ]
