# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0010_auto_20180416_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='jobs',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
