# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0013_auto_20180417_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_dmg_dealt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_dmg_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
