# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0016_auto_20180417_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_char',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dead_chars',
        ),
        migrations.AddField(
            model_name='char',
            name='active_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='active_char', to='dungeon_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='char',
            name='deaths',
            field=models.ManyToManyField(related_name='dead_chars', to='dungeon_app.User'),
        ),
    ]
