# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0017_auto_20180417_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
