# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0019_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='image',
            field=models.ImageField(upload_to='monsters'),
        ),
    ]
