# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0020_auto_20180417_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='items'),
            preserve_default=False,
        ),
    ]
