# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0021_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='active_user',
        ),
        migrations.RemoveField(
            model_name='char',
            name='deaths',
        ),
        migrations.AddField(
            model_name='user',
            name='active_char',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to='dungeon_app.Char'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dead_chars',
            field=models.ManyToManyField(related_name='death', to='dungeon_app.Char'),
        ),
    ]
