# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0023_auto_20180418_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_char',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to='dungeon_app.Char'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dead_chars',
            field=models.ManyToManyField(blank=True, related_name='death', to='dungeon_app.Char'),
        ),
    ]
