# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0025_auto_20180418_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to='dungeon_app.Char'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dead_chars',
            field=models.ManyToManyField(null=True, related_name='death', to='dungeon_app.Char'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monsters_killed',
            field=models.ManyToManyField(default='', null=True, related_name='slayers', to='dungeon_app.Mon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_dmg_dealt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_dmg_taken',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
