# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0027_auto_20180418_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='monsters_killed',
            field=models.TextField(null=True),
        ),
    ]
