# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0028_char_monsters_killed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monsters_killed',
        ),
        migrations.AddField(
            model_name='user',
            name='monsters_killed',
            field=models.TextField(null=True),
        ),
    ]
