# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0029_auto_20180418_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='characters',
            field=models.ManyToManyField(related_name='created_by', to='dungeon_app.Char'),
        ),
    ]
