# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0033_auto_20180418_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monsters_killed',
        ),
        migrations.AddField(
            model_name='char',
            name='num_monsters_killed',
            field=models.IntegerField(default=0),
        ),
    ]
