# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0036_auto_20180418_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_bosses_killed',
            field=models.IntegerField(default=0),
        ),
    ]
