# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0037_user_total_bosses_killed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='char',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dungeon_app.Job'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='jobs',
        ),
        migrations.AddField(
            model_name='item',
            name='jobs',
            field=models.ManyToManyField(related_name='items', to='dungeon_app.Job'),
        ),
    ]
