# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0038_auto_20180419_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='char',
            name='monsters_killed',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
