# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0039_auto_20180419_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='num_monsters_killed',
        ),
        migrations.AddField(
            model_name='mon',
            name='current_vitality',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='char',
            name='monsters_killed',
        ),
        migrations.AddField(
            model_name='char',
            name='monsters_killed',
            field=models.ManyToManyField(blank=True, related_name='slayers', to='dungeon_app.Mon'),
        ),
    ]
