# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0040_auto_20180420_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon',
            name='image_dead',
            field=models.ImageField(blank=True, upload_to='monsters'),
        ),
    ]
