# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0041_mon_image_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='characters', to='dungeon_app.Item'),
        ),
    ]
