# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon_app', '0042_auto_20180420_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='items', to='dungeon_app.Job'),
        ),
    ]
